<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="QA_Alok-PC-83" name="alok" tests="5" failures="2" timestamp="26 Apr 2019 06:29:09 GMT" time="0.831" errors="0">
  <testcase name="test" time="0.015" classname="test.aLOK"/>
  <testcase name="test1" time="0.002" classname="test.aLOK">
    <failure type="java.lang.AssertionError" message="expected [a] but found [an]">
      <![CDATA[java.lang.AssertionError: expected [a] but found [an]
	at test.aLOK.test1(aLOK.java:19)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="call" time="0.004" classname="test.Extent">
    <failure type="java.lang.AssertionError" message="expected [a] but found [an]">
      <![CDATA[java.lang.AssertionError: expected [a] but found [an]
	at test.aLOK.test1(aLOK.java:19)
	at test.Extent.call(Extent.java:59)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- call -->
  <testcase name="test123" time="0.0" classname="test.Extent"/>
  <testcase name="test1234" time="0.001" classname="test.Extent"/>
</testsuite> <!-- alok -->
